In [ ]:
import numpy as np
import pandas as pd
from scipy import stats as st

In [ ]:
frequencia_observada = np.array([80., 20.,	30.,	35.,	28.,	100., 150.])
frequencia_observada

array([ 80.,  20.,  30.,  35.,  28., 100., 150.])

In [ ]:
percentual_esperado = np.array([0.25, 0.05, 0.10,	0.10,	0.10,	0.15, 0.25])
percentual_esperado

array([0.25, 0.05, 0.1 , 0.1 , 0.1 , 0.15, 0.25])

In [ ]:
frequencia_esperada = np.sum(frequencia_observada) * percentual_esperado
frequencia_esperada

array([110.75,  22.15,  44.3 ,  44.3 ,  44.3 ,  66.45, 110.75])

In [ ]:
st.chisquare(frequencia_observada, frequencia_esperada)

Power_divergenceResult(statistic=52.161775771256586, pvalue=1.730222255796706e-09)

In [ ]:
dados_tratamentos = pd.read_csv('dados_tratamentos.csv', sep = ';')
dados_tratamentos.head()

id   tratamento      evolucao
0   1      tratado      melhorou
1   2      tratado      melhorou
2   3  nao-tratado      melhorou
3   4      tratado      melhorou
4   5      tratado  nao-melhorou

In [ ]:
tabela_cruzada = pd.crosstab(dados_tratamentos['tratamento'],
                            dados_tratamentos['evolucao'])
tabela_cruzada

evolucao     melhorou  nao-melhorou
tratamento                         
nao-tratado        26            29
tratado            35            15

In [ ]:
estatistica, p_value, gl, freq_esp = st.chi2_contingency(tabela_cruzada, correction = False)

In [ ]:
freq_esp

array([[31.95238095, 23.04761905],
       [29.04761905, 20.95238095]])

In [ ]:
gl

1

In [ ]:
p_value

0.018407774251540804

In [ ]:
estatistica

5.556919794065845