<a href="https://colab.research.google.com/github/lucaspinheiro27/MACHINE_LEARNING_DATA_SCIENCE/blob/main/squared.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Squared Numbers

In [1]:
def squared (x):
  return x**2

for ii in range(6):
  print(ii, squared(ii))

print("Done")

0 0
1 1
2 4
3 9
4 16
5 25
Done


# Python data structures

* Tuple( )

In [2]:
import numpy as np
# Tuples are immutable
#           0            1             2
mytuple = ('abc', np.arange(0,3,0.2), 2.5)

mytuple[2]

2.5

* Lists [ ]

In [3]:
mylist = ['abc', 'def', 'ghij']

mylist.append('klm')

print(mylist)

['abc', 'def', 'ghij', 'klm']


In [4]:
mylist2 = [1,2,3]
mylist3 = [4,5,6]

mylist2 + mylist3

[1, 2, 3, 4, 5, 6]

* Array[ ]

In [5]:
myarray2 = np.array(mylist2)
myarray3 = np.array(mylist3)

myarray2 + myarray3

array([5, 7, 9])

In [6]:
myarray2.dot(myarray3)

32

* Dictionary { }

In [7]:
mydict = dict(one=1, two=2, info='some information')
mydict2 = {'ten':1, 'twenty':20, 'info':'more information'}

In [8]:
mydict['info']

'some information'

In [9]:
mydict.keys()

dict_keys(['one', 'two', 'info'])

* Vectors and Arrays

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.arange(3)

array([0, 1, 2])

In [13]:
#         s e  si
np.arange(1,3,0.5)

array([1. , 1.5, 2. , 2.5])

In [14]:
xlow = np.arange(0,3, 0.5)
xhigh = np.arange(3,5,0.5)

In [15]:
xlow

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [16]:
xhigh

array([3. , 3.5, 4. , 4.5])

In [17]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [19]:
Amat = np.array([[1,2],
                 [3,4]])

In [21]:
Amat[0] #first row only

array([1, 2])

In [23]:
x = np.arange(3)
Amat = np.array([[1,2], [3,4]])

In [24]:
x.T == x

array([ True,  True,  True])

In [26]:
Amat.T == Amat

array([[ True, False],
       [False,  True]])

# Functions

In [31]:
#Definindo a função
def incomeandexpenses(data):

#A soma dos dados não pode ser menor ou igual zero
  income = np.sum(data[data>0])
#A soma dos dados tem que ser menor ou igual a zero
  expenses = np.sum(data[data<0])
#retorna a função
  return (income, expenses)

#solução para evitar erro de importação de módulos
if __name__=='__main__':
  testData = np.array([-5, 12, 3, -6, -4, 8])
#Verifica se a primeira transação foi uma perda de faz um delete
  if testData[0] < 0:
    print('Yout first transaction was a loss, and will be dropped')
    testData = np.delete(testData, 0)
  else:
    print('Congratulations: Your first transaction was a gain!')
#se for ganho ele printa, em seguida ele adiciona em outras duas variáveis de acordo com os dados testes
  (myincome, myexpenses) = incomeandexpenses(testData)
  print('You have earned {0:5.2f} EUR, and spent {1:5.2f} EUR.'.format(myincome, -myexpenses))

Yout first transaction was a loss, and will be dropped
You have earned 23.00 EUR, and spent 10.00 EUR.
